language: php

php:
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.6 WP_MULTISITE=0
    - WP_VERSION=4.5 WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
